INSERT INTO `schools`(id, name, domain, logo_url) VALUES (1, 'Cphbusiness', 'cphbusiness.dk', 'https://codergram.me/cphbusiness.png');
INSERT INTO `schools`(id, name, domain, logo_url) VALUES (2, 'KEA', 'kea.dk', 'https://codergram.me/kea.jpg');
INSERT INTO `schools`(id, name, domain, logo_url) VALUES (3, 'DTU', 'dtu.dk', 'https://codergram.me/dtu.png');
INSERT INTO `schools`(id, name, domain, logo_url) VALUES (4, 'CBS', 'cbs.dk', 'https://codergram.me/cbs.png');

INSERT INTO `courses` VALUES (1, 'Datamatiker', 1);
INSERT INTO `courses` VALUES (2, 'Finansøkonom', 1);
INSERT INTO `courses` VALUES (3, 'Multimediedesigner', 1);
INSERT INTO `courses` VALUES (4, 'Datamatiker', 2);
INSERT INTO `courses` VALUES (5, 'Finansøkonom', 2);
INSERT INTO `courses` VALUES (6, 'Multimediedesigner', 2);
INSERT INTO `courses` VALUES (7, 'Elektroteknologi', 3);
INSERT INTO `courses` VALUES (8, 'IT-Elektronik', 3);
INSERT INTO `courses` VALUES (9, 'Bygningsdesigner', 3);
INSERT INTO `courses` VALUES (10, 'HA-Fil', 4);
INSERT INTO `courses` VALUES (11, 'HA-Kom', 4);
INSERT INTO `courses` VALUES (12, 'HA-Dat', 4);

INSERT INTO `semesters` VALUES (1, '1. Semester', 1);
INSERT INTO `semesters` VALUES (2, '2. Semester', 1);
INSERT INTO `semesters` VALUES (3, '3. Semester', 1);
INSERT INTO `semesters` VALUES (4, '4. Semester', 1);
INSERT INTO `semesters` VALUES (5, '5. Semester', 1);
INSERT INTO `semesters` VALUES (6, '1. Semester', 2);
INSERT INTO `semesters` VALUES (7, '2. Semester', 2);
INSERT INTO `semesters` VALUES (8, '3. Semester', 2);
INSERT INTO `semesters` VALUES (9, '4. Semester', 2);
INSERT INTO `semesters` VALUES (10, '5. Semester', 2);
INSERT INTO `semesters` VALUES (11, '1. Semester', 3);
INSERT INTO `semesters` VALUES (12, '2. Semester', 3);
INSERT INTO `semesters` VALUES (13, '3. Semester', 3);
INSERT INTO `semesters` VALUES (14, '4. Semester', 3);
INSERT INTO `semesters` VALUES (15, '5. Semester', 3);
INSERT INTO `semesters` VALUES (16, '1. Semester', 4);
INSERT INTO `semesters` VALUES (17, '2. Semester', 4);
INSERT INTO `semesters` VALUES (18, '3. Semester', 4);
INSERT INTO `semesters` VALUES (19, '4. Semester', 4);
INSERT INTO `semesters` VALUES (20, '5. Semester', 4);
INSERT INTO `semesters` VALUES (21, '1. Semester', 5);
INSERT INTO `semesters` VALUES (22, '2. Semester', 5);
INSERT INTO `semesters` VALUES (23, '3. Semester', 5);
INSERT INTO `semesters` VALUES (24, '4. Semester', 5);
INSERT INTO `semesters` VALUES (25, '5. Semester', 5);
INSERT INTO `semesters` VALUES (26, '1. Semester', 6);
INSERT INTO `semesters` VALUES (27, '2. Semester', 6);
INSERT INTO `semesters` VALUES (28, '3. Semester', 6);
INSERT INTO `semesters` VALUES (29, '4. Semester', 6);
INSERT INTO `semesters` VALUES (30, '5. Semester', 6);
INSERT INTO `semesters` VALUES (31, '1. Semester', 7);
INSERT INTO `semesters` VALUES (32, '2. Semester', 7);
INSERT INTO `semesters` VALUES (33, '3. Semester', 7);
INSERT INTO `semesters` VALUES (34, '4. Semester', 7);
INSERT INTO `semesters` VALUES (35, '5. Semester', 7);
INSERT INTO `semesters` VALUES (36, '1. Semester', 8);
INSERT INTO `semesters` VALUES (37, '2. Semester', 8);
INSERT INTO `semesters` VALUES (38, '3. Semester', 8);
INSERT INTO `semesters` VALUES (39, '4. Semester', 8);
INSERT INTO `semesters` VALUES (40, '5. Semester', 8);
INSERT INTO `semesters` VALUES (41, '1. Semester', 9);
INSERT INTO `semesters` VALUES (42, '2. Semester', 9);
INSERT INTO `semesters` VALUES (43, '3. Semester', 9);
INSERT INTO `semesters` VALUES (44, '4. Semester', 9);
INSERT INTO `semesters` VALUES (45, '5. Semester', 9);
INSERT INTO `semesters` VALUES (46, '1. Semester', 10);
INSERT INTO `semesters` VALUES (47, '2. Semester', 10);
INSERT INTO `semesters` VALUES (48, '3. Semester', 10);
INSERT INTO `semesters` VALUES (49, '4. Semester', 10);
INSERT INTO `semesters` VALUES (50, '5. Semester', 10);
INSERT INTO `semesters` VALUES (51, '6. Semester', 10);
INSERT INTO `semesters` VALUES (52, '1. Semester', 11);
INSERT INTO `semesters` VALUES (53, '2. Semester', 11);
INSERT INTO `semesters` VALUES (54, '3. Semester', 11);
INSERT INTO `semesters` VALUES (55, '4. Semester', 11);
INSERT INTO `semesters` VALUES (56, '5. Semester', 11);
INSERT INTO `semesters` VALUES (57, '6. Semester', 11);
INSERT INTO `semesters` VALUES (58, '1. Semester', 12);
INSERT INTO `semesters` VALUES (59, '2. Semester', 12);
INSERT INTO `semesters` VALUES (60, '3. Semester', 12);
INSERT INTO `semesters` VALUES (61, '4. Semester', 12);
INSERT INTO `semesters` VALUES (62, '5. Semester', 12);
INSERT INTO `semesters` VALUES (63, '6. Semester', 12);

INSERT INTO `teachers` VALUES (1, 'teacher@cphbusiness.dk', 'Teacher CPHBUSINESS', '1234', 'https://zoom.us/cphbusiness');
INSERT INTO `teachers` VALUES (2, 'teacher@kea.dk', 'Teacher KEA', '1234', 'https://zoom.us/kea');
INSERT INTO `teachers` VALUES (3, 'teacher@dtu.dk', 'Teacher DTU', '1234', 'https://zoom.us/dtu');
INSERT INTO `teachers` VALUES (4, 'teacher@cbs.dk', 'Teacher CBS', '1234', 'https://zoom.us/cbs');

INSERT INTO `students` VALUES (1, 'arik@cphbusiness.dk', 'Arik cphbusiness');
INSERT INTO `students` VALUES (2, 'arik@cbs.dk', 'Arik cbs');
INSERT INTO `students` VALUES (3, 'arik@kea.dk', 'Arik kea');
INSERT INTO `students` VALUES (4, 'arik@dtu.dk', 'Arik dtu');
INSERT INTO `students` VALUES (5, 'cph-ap322@cphbusiness.dk', 'Alexander Hüsig Petersen');
INSERT INTO `students` VALUES (6, 'cph-ac221@cphbusiness.dk', 'Anne Cathrine Høyer Christensen');
INSERT INTO `students` VALUES (7, 'cph-ct139@cphbusiness.dk', 'Casper Sophus Thomassen');
INSERT INTO `students` VALUES (8, 'cph-ew45@cphbusiness.dk', 'Emil Alexander Westergård');
INSERT INTO `students` VALUES (9, 'cph-ej142@cphbusiness.dk', 'Emil Dyrhøi Tolderlund Jørgensen');
INSERT INTO `students` VALUES (10, 'cph-en93@cphbusiness.dk', 'Emil Elkjær Nielsen');
INSERT INTO `students` VALUES (11, 'cph-gb77@cphbusiness.dk', 'Gustav Ejby Bidstrup');
INSERT INTO `students` VALUES (12, 'cph-hs228@cphbusiness.dk', 'Hallur Simonsen');
INSERT INTO `students` VALUES (13, 'cph-jj484@cphbusiness.dk', 'Jack Hagedorn Jensen');
INSERT INTO `students` VALUES (14, 'cph-jp385@cphbusiness.dk', 'Jacob Bay Petersen');
INSERT INTO `students` VALUES (15, 'cph-jn352@cphbusiness.dk', 'Jacob Lange Nielsen');
INSERT INTO `students` VALUES (16, 'cph-jr270@cphbusiness.dk', 'Janus Stivang Rasmussen');
INSERT INTO `students` VALUES (17, 'cph-jg162@cphbusiness.dk', 'Jens Frederik Gelbek');
INSERT INTO `students` VALUES (18, 'cph-jb361@cphbusiness.dk', 'Jens Ohlendorff Brønd');
INSERT INTO `students` VALUES (19, 'cph-js438@cphbusiness.dk', 'Jonas Mik Soldath');
INSERT INTO `students` VALUES (20, 'cph-lp262@cphbusiness.dk', 'Lars Krogh Poulsen');
INSERT INTO `students` VALUES (21, 'cph-mt326@cphbusiness.dk', 'Mathias Baumann Toubøl');
INSERT INTO `students` VALUES (22, 'cph-mp557@cphbusiness.dk', 'Mathias Enemark Poulsen');
INSERT INTO `students` VALUES (23, 'cph-mh881@cphbusiness.dk', 'Mathias Hvid');
INSERT INTO `students` VALUES (24, 'cph-nt105@cphbusiness.dk', 'Nikolaj Trankjær');
INSERT INTO `students` VALUES (25, 'cph-pa127@cphbusiness.dk', 'Peter Rambeck Andersen');
INSERT INTO `students` VALUES (26, 'cph-rh191@cphbusiness.dk', 'Rasmus Ditlev Hansen');
INSERT INTO `students` VALUES (27, 'cph-ro53@cphbusiness.dk', 'Rasmus Olsson');
INSERT INTO `students` VALUES (28, 'cph-at89@cphbusiness.dk', 'Sigurd Arik Gaarde Nielsen');
INSERT INTO `students` VALUES (29, 'cph-sa343@cphbusiness.dk', 'Søren Due Andersen');
INSERT INTO `students` VALUES (30, 'cph-tb237@cphbusiness.dk', 'Tamana Barakzai');
INSERT INTO `students` VALUES (31, 'cph-tz11@cphbusiness.dk', 'Tobias Zimmermann');
INSERT INTO `students` VALUES (32, 'cph-aa394@cphbusiness.dk', 'Abdi Zamad Mohamad Jama Abdulle');
INSERT INTO `students` VALUES (33, 'cph-as559@cphbusiness.dk', 'Aleksander Storm');
INSERT INTO `students` VALUES (34, 'cph-ak428@cphbusiness.dk', 'Alex Simone Kenfelt');
INSERT INTO `students` VALUES (35, 'cph-aj405@cphbusiness.dk', 'Annika Rosenvinge Jespersen');
INSERT INTO `students` VALUES (36, 'cph-bs202@cphbusiness.dk', 'Benjamin Ritthidech Sommervoll');
INSERT INTO `students` VALUES (37, 'cph-dd77@cphbusiness.dk', 'Daniel Anders Drobek');
INSERT INTO `students` VALUES (38, 'cph-ea120@cphbusiness.dk', 'Emil Ruby Andersen');
INSERT INTO `students` VALUES (39, 'cph-fk99@cphbusiness.dk', 'Firat Kayaalp');
INSERT INTO `students` VALUES (40, 'cph-fs101@cphbusiness.dk', 'Florian Michael Schaffer');
INSERT INTO `students` VALUES (41, 'cph-fa116@cphbusiness.dk', 'Frederik Bilgrav Andersen');
INSERT INTO `students` VALUES (42, 'cph-js485@cphbusiness.dk', 'Jacob Volck Sinding');
INSERT INTO `students` VALUES (43, 'cph-sp341@cphbusiness.dk', 'Jonathan Köhl Pedersen');
INSERT INTO `students` VALUES (44, 'cph-jm352@cphbusiness.dk', 'Julius Krüger Madsen');
INSERT INTO `students` VALUES (45, 'cph-le115@cphbusiness.dk', 'Louise Sitting Estrup');
INSERT INTO `students` VALUES (46, 'cph-mn605@cphbusiness.dk', 'Maja Nøhr-Nørgaard');
INSERT INTO `students` VALUES (47, 'cph-mm620@cphbusiness.dk', 'Maria Theresa Udengaard Mc Nally');
INSERT INTO `students` VALUES (48, 'cph-ma587@cphbusiness.dk', 'Markus Agnsgaard');
INSERT INTO `students` VALUES (49, 'cph-mg320@cphbusiness.dk', 'Mikkel Gunge Gottschalck');
INSERT INTO `students` VALUES (50, 'cph-mt357@cphbusiness.dk', 'Mustafa Tokmak');
INSERT INTO `students` VALUES (51, 'cph-nm172@cphbusiness.dk', 'Nicolai Gissel Martini');
INSERT INTO `students` VALUES (52, 'cph-oj92@cphbusiness.dk', 'Oliver Martin Husted Jenbo');
INSERT INTO `students` VALUES (53, 'cph-oj93@cphbusiness.dk', 'Oliver Roat Jørgensen');
INSERT INTO `students` VALUES (54, 'cph-rd92@cphbusiness.dk', 'Rasmus Dalgaard');
INSERT INTO `students` VALUES (55, 'cph-rp154@cphbusiness.dk', 'Robert Pallesen');
INSERT INTO `students` VALUES (56, 'cph-ta181@cphbusiness.dk', 'Thomas Steen Amorsen');
INSERT INTO `students` VALUES (57, 'cph-aj419@cphbusiness.dk', 'Albert Emil Hyrde Jensen');
INSERT INTO `students` VALUES (58, 'cph-ak433@cphbusiness.dk', 'Albert Havn Kops');
INSERT INTO `students` VALUES (59, 'cph-al351@cphbusiness.dk', 'Aleksander Christian Rolander Langkjær');
INSERT INTO `students` VALUES (60, 'cph-ab458@cphbusiness.dk', 'Andreas Buch');
INSERT INTO `students` VALUES (61, 'cph-aw125@cphbusiness.dk', 'Andreas Villemoes Weidekamp');
INSERT INTO `students` VALUES (62, 'cph-ad228@cphbusiness.dk', 'August Christoffer Bredahl Duelund');
INSERT INTO `students` VALUES (63, 'cph-cr272@cphbusiness.dk', 'Christian Schaadt Rosenbæk');
INSERT INTO `students` VALUES (64, 'cph-cq2@cphbusiness.dk', 'Christoffer Munk Quakernaat');
INSERT INTO `students` VALUES (65, 'cph-dp134@cphbusiness.dk', 'Daniel Weiss Pedersen');
INSERT INTO `students` VALUES (66, 'cph-ed79@cphbusiness.dk', 'Ermin Dzafic');
INSERT INTO `students` VALUES (67, 'cph-hm163@cphbusiness.dk', 'Hans-Henrik Lübcke Storm Madsen');
INSERT INTO `students` VALUES (68, 'cph-jo163@cphbusiness.dk', 'Jens Christian Øgaard');
INSERT INTO `students` VALUES (69, 'cph-jb403@cphbusiness.dk', 'Jaan Adam von Magius Butt');
INSERT INTO `students` VALUES (70, 'cph-lo140@cphbusiness.dk', 'Lukas Benike Okholm');
INSERT INTO `students` VALUES (71, 'cph-mk682@cphbusiness.dk', 'Mads Teddy Francois Knudsen');
INSERT INTO `students` VALUES (72, 'cph-mg319@cphbusiness.dk', 'Magnus Braas Granno');
INSERT INTO `students` VALUES (73, 'cph-md266@cphbusiness.dk', 'Mathias Brix Drejer');
INSERT INTO `students` VALUES (74, 'cph-mj839@cphbusiness.dk', 'Mathias Egebjerg Jensen');
INSERT INTO `students` VALUES (75, 'cph-mf287@cphbusiness.dk', 'Mathias Fantoni');
INSERT INTO `students` VALUES (76, 'cph-mh914@cphbusiness.dk', 'Mathias Filtenborg Hansen');
INSERT INTO `students` VALUES (77, 'cph-mj838@cphbusiness.dk', 'Mikkel Dahl Jacobsen');
INSERT INTO `students` VALUES (78, 'cph-or42@cphbusiness.dk', 'Oliver Juul Reder');
INSERT INTO `students` VALUES (79, 'cph-os85@cphbusiness.dk', 'Oliver Veng Stæhr');
INSERT INTO `students` VALUES (80, 'cph-pt124@cphbusiness.dk', 'Peter Andersen');
INSERT INTO `students` VALUES (81, 'cph-se126@cphbusiness.dk', 'Sebastian Fahrenholtz Engelbrecht');
INSERT INTO `students` VALUES (82, 'cph-sh528@cphbusiness.dk', 'Sebastian Hejlesen');
INSERT INTO `students` VALUES (83, 'cph-tp208@cphbusiness.dk', 'Thias Meyer Petersen');
INSERT INTO `students` VALUES (84, 'cph-tl233@cphbusiness.dk', 'Tobias Jensen Linge');
INSERT INTO `students` VALUES (85, 'cph-am8@cphbusiness.dk', 'Alexander Stub Michelsen');
INSERT INTO `students` VALUES (86, 'cph-am382@cphbusiness.dk', 'August Manniche Møller');
INSERT INTO `students` VALUES (87, 'cph-jv124@cphbusiness.dk', 'Jens-Olof Pingel Vogel');
INSERT INTO `students` VALUES (88, 'cph-jk389@cphbusiness.dk', 'Johan Dam Karpantschof');
INSERT INTO `students` VALUES (89, 'cph-kd131@cphbusiness.dk', 'Kasper Overgaard Dahl');
INSERT INTO `students` VALUES (90, 'cph-kp261@cphbusiness.dk', 'Kristoffer Borg Pauly');
INSERT INTO `students` VALUES (91, 'cph-nb209@cphbusiness.dk', 'Nicholas Birk Broch');
INSERT INTO `students` VALUES (92, 'cph-na181@cphbusiness.dk', 'Nicklas Boelhøj Andersen');
INSERT INTO `students` VALUES (93, 'cph-op69@cphbusiness.dk', 'Ole Højgaard Pedersen');
INSERT INTO `students` VALUES (94, 'cph-rh206@cphbusiness.dk', 'Ruimin Huang');
INSERT INTO `students` VALUES (95, 'cph-sb442@cphbusiness.dk', 'Søren Aagaard Bendtsen');
INSERT INTO `students` VALUES (96, 'cph-tm246@cphbusiness.dk', 'Timothy Busk Mortensen');
INSERT INTO `students` VALUES (97, 'cph-yk31@cphbusiness.dk', 'Younes Karim');
INSERT INTO `students` VALUES (98, 'cph-mf282@cphbusiness.dk', 'Mo Futtrup');
INSERT INTO `students` VALUES (99, 'cph-al350@cphbusiness.dk', 'Anders Bidstrup Lind');
INSERT INTO `students` VALUES (100, 'cph-ln288@cphbusiness.dk', 'Lukas Bo Nielsen');
INSERT INTO `students` VALUES (101, 'cph-nh192@cphbusiness.dk', 'Nicklas Kofoed Hansen');
INSERT INTO `students` VALUES (102, 'cph-nb191@cphbusiness.dk', 'Nicklas Lambrecht Bergmann-Holm');
INSERT INTO `students` VALUES (103, 'cph-pt123@cphbusiness.dk', 'Peter Lønquist Thomasen');
INSERT INTO `students` VALUES (104, 'cph-ra147@cphbusiness.dk', 'René Stefaniuk Andersen');
INSERT INTO `students` VALUES (105, 'cph-sl240@cphbusiness.dk', 'Simon Christian Lund');
INSERT INTO `students` VALUES (106, 'cph-sn286@cphbusiness.dk', 'Simon Nielsen');
INSERT INTO `students` VALUES (107, 'cph-to83@cphbusiness.dk', 'Thomas Schwencke Overgaard');
INSERT INTO `students` VALUES (108, 'cph-tj308@cphbusiness.dk', 'Thorbjørn Jensen');
INSERT INTO `students` VALUES (109, 'cph-wk7@cphbusiness.dk', 'Wehba Salem Korouni');